"""
Base interface for all Large Language Model (LLM) clients.

This module defines the contract that every LLM provider
(Gemini, OpenAI, Claude, Ollama, etc.) must implement.

The goal is to keep the business logic independent from
any specific LLM provider.
"""

from abc import ABC, abstractmethod


class BaseLLM(ABC):
    """
    Abstract base class for all LLM clients.
    """

    @abstractmethod
    def generate(
        self,
        system_prompt: str,
        user_prompt: str,
    ) -> str:
        """
        Generate a text response from the LLM.

        Parameters
        ----------
        system_prompt : str
            High-level instruction defining the AI behavior.

        user_prompt : str
            User request or task input.

        Returns
        -------
        str
            Raw text response generated by the LLM.
        """
        pass

    @abstractmethod
    def health_check(self) -> bool:
        """
        Check whether the LLM service is available.

        Returns
        -------
        bool
            True if the service is healthy.
        """
        pass