"""
Gemini LLM client implementation.

This module provides an implementation of the BaseLLM interface
using Google's Gemini API.
"""

from google import genai

from app.llm.base_llm import BaseLLM
from app.utils.config import GEMINI_API_KEY, GEMINI_MODEL
from app.utils.logger import setup_logger


class GeminiClient(BaseLLM):
    """
    Google Gemini implementation of the BaseLLM interface.
    """

    def __init__(self):
        self.logger = setup_logger(self.__class__.__name__)

        # Fail fast if API key is missing
        if not GEMINI_API_KEY:
            raise ValueError(
                "GEMINI_API_KEY is not configured."
            )

        self.client = genai.Client(
            api_key=GEMINI_API_KEY
        )

        self.model_name = GEMINI_MODEL

    def generate(
        self,
        system_prompt: str,
        user_prompt: str,
    ) -> str:
        """
        Generate a response from Gemini.

        Parameters
        ----------
        system_prompt : str
            High-level instruction defining the AI behavior.

        user_prompt : str
            User request or input.

        Returns
        -------
        str
            Response generated by Gemini.
        """

        self.logger.info("Generating Gemini response...")

        response = self.client.models.generate_content(
            model=self.model_name,
            contents=user_prompt,
            config={
                "system_instruction": system_prompt,
                "temperature": 0.2,
            },
        )

        return response.text or ""

    def health_check(self) -> bool:
        """
        Verify that Gemini API is reachable.

        Returns
        -------
        bool
            True if Gemini is available.
        """

        try:
            self.generate(
                system_prompt="You are a helpful assistant.",
                user_prompt="Reply with exactly: OK",
            )

            self.logger.info(
                "Gemini health check passed."
            )

            return True

        except Exception as e:
            self.logger.error(
                f"Gemini health check failed: {e}"
            )
            return False